language: node_js
node_js: node
services:
- mongodb
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: wjXeK/8lGun/X2xtR8tMGhdsgUMUlddRQQzjLGtmrH4R2J45ko7JNFGBufqosUtABcHqwlbg6pEEXz6OtSEWqReB7kdkQ/DBqXr0ytszkpeWtOs5f0FfP7cq8Ot5Pg2CTd/2Ef2vV0iDO3XsDfZ/DJQts3ry2ZT8GFPtCO1kmRfSngaRCDI+KDYJ7no1gL7jfy+k9EJM/qzn5JyY9Y2LVLnUIMCk/wHWx+Z8b4ykfwKUe/m8SQGDKHQkgbNtvRSdx3dtYYrdHuTjDr4RIPlD6KC3/j3EcRXP5/erZxUaU+Qu0wggAj8rmvRU6sel01XVsA8yo5YmH33eT7/Cb0OqlnmSlUKBYsQi0OtlXAUVDRD/hRr5k5fU1ztZ85pzUlfT/642jqwgWDICKmqWqUMZQVhEpTEb98qof9SLwNMV7Uk3Z37LL7ewarWRgNFvKYvfwHKA9tf+U5e4jTcrGGoe8FfEjaHCItx+d+3s6hjQi3w8LLieuZnpjYpeVQj8SZEWprqqUziRQt7b0yc0gEbrX/jjiZjWHoeVZ0qxwUK2h4fEBDVWKEJ1HKvCM2leDX4yJAQCXDMakW21GQlW8DMMvNHuutfdoa2bDVfJdxQ1TeSWLlF8Yeqy3vGiimDM7Lkt3hndiMp04jGo7UIx7YTLoP6rU9pmQ4SsZCC8anAKT4E=
