language: node_js
node_js: node
services:
- mongodb
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: h+Yd988QemKCyzH9Pbr8qRn+z7u/Jl/93Rff7im/R+kPmDDeSk2ogmUTK4UlSyfXyWiD/c+rZ2rPkJ8OiZJHPnMhilOkPydrKM83AXLlVpjF9b+IcsQEuv82cir/uR/fnewv8dDiG/LtH2vXtXMs9PQpgRfumocbmi8F6lne+sAALigCbGtyJIz9Y75Yu0P1XOFB9Zbqo1V8nApx+SLMfskW/ZX5WjcPU/KjKoOzJ8+BFMlMvq2dI6v/UYSJHfXcBliNBUTlD7TPyQF9aDRijVtvNWA7DBid75CdQRt9VsYEJPyvz54Unlf28gwn2P3JyQ7tw9QQtVLn994uFWV2wTsI3Zzd9YvDQFXTPiSA98J9r/IJxEpChkjYodRikz31WzB+jJBExU9Wbq/0QSXvw8Ek6P+bYGRU0suSoJgGt3Z0Ww8SuuanYnm9+fZDexYbTJJWMwZdm5JH+D8eK+1gr1S97RyX5z65L7NMt2mP2HvaOAsozvIST0erNLxY47dP5IonQqmi1mZqmpBRdFWNURz7joOua5VR0Fb6qPa4uqKPh5pWYCOhkMrpLNJsHeDO812zobN29VTWjtLmVVmjGoXX9W3o8mzluFJp0sXm2o2JPAmT5T0lkwtKRyY0sU306EqWb2oT2yajcBOstjCj0BfmU8nHkE0utXpyuyEDyco=